version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: taskflow-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskflow
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskflow-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGODB_URI: mongodb://mongodb:27017/taskflow
      JWT_SECRET: supersecret_taskflow_jwt_key_2026_dev_prod
      CLIENT_URL: http://localhost:3000
      NODE_ENV: production
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskflow-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
